ClinicServiceSystem/Controllers/ClinicQueryController.cs
using ClinicServiceSystem.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClinicServiceSystem.Controllers
{
    public class ClinicQueryController : SharedController
    {
        ClinicServiceWebService.ClinicService svc = new ClinicServiceWebService.ClinicService();

        // GET: ClinicQuery
        override public ActionResult Index()
        {
            Clinic model = new Clinic()
            {
                ClinicTypeSelectList = GetSelectList(svc.SelectKeyCodeClinicType(), ""),
                ServiceTypeSelectList = GetSelectList(svc.SelectKeyCodeServiceType(), ""),
                OutPatientTypeSelectList = GetSelectList(svc.SelectKeyCodeOutPatientType(), ""),
                CoopTypeSelectList = GetSelectList(svc.SelectKeyCodeCoopType(), ""),
                BusinessHourSelectList = GetSelectList(svc.SelectKeyCodeBusinessTime(), "")
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Search(Clinic model)
        {
            Result result = new Result();

            try
            {
                List<Clinic> lstResult = new List<Clinic>();
                DataTable dtQuery = svc.SelectClinic(model.ClinicName, model.ClinicType, model.ServiceType, model.OutPatientType, model.BusinessHour);

                foreach(DataRow dr in dtQuery.Rows)
                {
                    lstResult.Add(new Clinic()
                    {
                        ClinicId = dr.Field<string>("clinic_id"),
                        ClinicName = dr.Field<string>("clinic_name"),
                        ClinicType = dr.Field<string>("clinic_type"),
                        ServiceType = dr.Field<string>("service_name"),
                        OutPatientType = dr.Field<string>("outpatient_name"),
                        CoopType = dr.Field<string>("coop_type_name"),

                        BusinessHour= dr.Field<string>("business_time_frame"),
                        Phone = dr.Field<string>("phone"),
                        Address = dr.Field<string>("remark"),
                        Remark = dr.Field<string>("address"),
                        DepartmentName = dr.Field<string>("department_name"),
                        CountyId = dr.Field<int?>("county_id"),
                    });
                }

                result.Data = JsonConvert.SerializeObject(lstResult);
                result.Success = true;
            }
            catch (Exception ex)
            {
                result.Success = false;
                result.Message = ex.Message;
            }

            return new JsonResult { Data = result };
        }

        [HttpPost]
        public ActionResult Action(Clinic model)
        {
            Result result = new Result();

            try
            {
                switch (model.OperCode)
                {
                    case "add":
                        model = new Clinic()
                        {
                            ClinicTypeSelectList = GetSelectList(svc.SelectKeyCodeClinicType(), ""),
                            ServiceTypeSelectList = GetSelectList(svc.SelectKeyCodeServiceType(), ""),
                            OutPatientTypeSelectList = GetSelectList(svc.SelectKeyCodeOutPatientType(), ""),
                            CoopTypeSelectList = GetSelectList(svc.SelectKeyCodeCoopType(), ""),
                            BusinessHourSelectList = GetSelectList(svc.SelectKeyCodeBusinessTime(), ""),

                            OperCode = model.OperCode
                        };

                        break;

                    case "detail":
                    case "edit":
                    case "delete":
                        DataTable dtQuery = svc.SelectClinicById(model.ClinicId);

                        model = new Clinic()
                        {
                            ClinicId = dtQuery.Rows[0].Field<string>("clinic_id"),
                            ClinicName = dtQuery.Rows[0].Field<string>("clinic_name"),
                            ClinicType = dtQuery.Rows[0].Field<string>("clinic_type"),
                            ServiceType = dtQuery.Rows[0].Field<string>("service_id"),
                            OutPatientType = dtQuery.Rows[0].Field<string>("outpatient_id"),
                            CoopType = dtQuery.Rows[0].Field<string>("coop_type_id"),
                            BusinessHour = dtQuery.Rows[0].Field<string>("business_time_id"),
                            Phone = dtQuery.Rows[0].Field<string>("phone"),
                            Address = dtQuery.Rows[0].Field<string>("address"),
                            Remark = dtQuery.Rows[0].Field<string>("remark"),
                            DepartmentName = dtQuery.Rows[0].Field<string>("department_name"),
                            CountyId = dtQuery.Rows[0].Field<int?>("county_id"),

                            ClinicTypeSelectList = GetSelectList(svc.SelectKeyCodeClinicType(), dtQuery.Rows[0].Field<string>("clinic_type")),
                            ServiceTypeSelectList = GetSelectList(svc.SelectKeyCodeServiceType(), dtQuery.Rows[0].Field<string>("service_id")),
                            OutPatientTypeSelectList = GetSelectList(svc.SelectKeyCodeOutPatientType(), dtQuery.Rows[0].Field<string>("outpatient_id")),
                            CoopTypeSelectList = GetSelectList(svc.SelectKeyCodeCoopType(), dtQuery.Rows[0].Field<string>("coop_type_id")),
                            BusinessHourSelectList = GetSelectList(svc.SelectKeyCodeBusinessTime(), dtQuery.Rows[0].Field<string>("business_time_id")),

                            OperCode = model.OperCode
                        };

                        break;

                    default:
                        break;
                }

                result.Data = RenderPartialViewToString("_PartialCRUD", model);
                result.Success = true;
            }
            catch (Exception ex)
            {
                result.Success = false;
                result.Message = ex.Message;
            }

            return new JsonResult { Data = result };
        }

        [HttpPost]
        public ActionResult Save(Clinic model)
        {
            Result result = new Result();

            try
            {
                string strMessage = string.Empty;

                switch (model.OperCode)
                {
                    case "add":
                        result.Success = svc.InsertClinic(model.ClinicName, model.ClinicType, model.ServiceType, model.OutPatientType, model.CoopType, model.BusinessHour, model.Phone, model.Address, model.Remark, model.DepartmentName, model.CountyId, out strMessage);
                        
                        break;

                    case "detail":
                        break;

                    case "edit":
                        result.Success = svc.UpdateClinic(model.ClinicId, model.ClinicName, model.ClinicType, model.ServiceType, model.OutPatientType, model.CoopType, model.BusinessHour, model.Phone, model.Address, model.Remark, model.DepartmentName, model.CountyId, out strMessage);
                        
                        break;

                    case "delete":
                        result.Success = svc.DeleteClinic(model.ClinicId, out strMessage);

                        break;

                    default:
                        break;
                }

                if (!result.Success)
                    throw new Exception(strMessage);
            }
            catch (Exception ex)
            {
                result.Success = false;
                result.Message = ex.Message;
            }

            return new JsonResult { Data = result };
        }
    }
}

ClinicServiceSystem/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClinicServiceSystem.Controllers
{
    public class FeedbackController : SharedController
    {
        // GET: Feedback
        override public ActionResult Index()
        {
            return View();
        }
    }
}

ClinicServiceSystem/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClinicServiceSystem.Controllers
{
    public class SharedController : Controller
    {
        // GET: Shared
        virtual public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// A Result contains what processed inneed in controller.
        /// </summary>
        public class Result
        {
            public bool Success { get; set; }
            public string Message { get; set; }
            public string Code { get; set; }
            public string Data { get; set; }

            public Result()
            {
                Success = false;
                Message = string.Empty;
                Code = string.Empty;
                Data = string.Empty;
            }
        }

        /// <summary>
        /// To generate an Html String with the certain View and View Model.
        /// </summary>
        /// <param name="viewName">The used partial view name.</param>
        /// <param name="viewModel">The used view model.</param>
        /// <returns>The Html String.</returns>
        virtual public string RenderPartialViewToString(string viewName, object viewModel)
        {
            if (string.IsNullOrEmpty(viewName))
            {
                viewName = ControllerContext.RouteData.GetRequiredString("action");
            }

            ViewData.Model = viewModel;

            using (var sw = new StringWriter())
            {
                ViewEngineResult viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);

                return sw.GetStringBuilder().ToString();
            }
        }

        /// <summary>
        /// Get the Select List from Enum Type.
        /// </summary>
        /// <param name="dtKeyValue">The DataTable of Key Value.</param>
        /// <param name="strSelected">The Selected Value.</param>
        /// <returns>The Select List.</returns>
        public SelectList GetSelectList(DataTable dtKeyValue, string strSelected)
        {
            List<string> lstSelected = string.IsNullOrEmpty(strSelected) ? new List<string>() : strSelected.Split(',').ToList();

            List<SelectListItem> selectListItems = new List<SelectListItem>();

            foreach (DataRow dr in dtKeyValue.AsEnumerable())
            {
                selectListItems.Add(new SelectListItem()
                {
                    Value = dr[0].ToString(),
                    Text = dr[1].ToString(),
                    Selected = lstSelected.Contains(dr[0].ToString())
                });
            }

            return new SelectList(selectListItems, "Value", "Text", lstSelected);
        }

        /// <summary>
        /// Get the Select List with a Empty selection from Enum Type.
        /// </summary>
        /// <param name="dtKeyValue">The DataTable of Key Value.</param>
        /// <param name="strSelected">The String of Selected Value.</param>
        /// <returns>The Select List.</returns>
        public SelectList GetSelectListWithEmpty(DataTable dtKeyValue, string strSelected)
        {
            List<string> lstSelected = string.IsNullOrEmpty(strSelected) ? new List<string>() : strSelected.Split(',').ToList();

            List<SelectListItem> selectListItems = new List<SelectListItem>()
            {
                new SelectListItem()
                {
                    Value = "",
                    Text = "",
                    Selected = lstSelected.Count.Equals(0)
                }
            };

            foreach (DataRow dr in dtKeyValue.AsEnumerable())
            {
                selectListItems.Add(new SelectListItem()
                {
                    Value = dr[0].ToString(),
                    Text = dr[1].ToString(),
                    Selected = lstSelected.Contains(dr[0].ToString())
                });
            }

            return new SelectList(selectListItems, "Value", "Text", lstSelected);
        }
    }
}

ClinicServiceSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<style type="text/css">
    /* Side Navigation Bar Start */
    #sidenav-bar {
        height: 100%;
        width: 50px;
        position: fixed;
        z-index: 1;
        top: 50px;
        left: 0px;
        background-color: #111;
        overflow-x: hidden;
        padding-top: 60px;
        transition: 0.5s;
    }

    #sidenav-bar.sidenav-bar-open {
        width: 240px;           /* Side Navigation Bar - This should be same. */
    }
    /* Side Navigation Bar End */
    
    /* Side Navigation Bar Context Link Start */
    #sidenav-bar a {
        padding: 8px 8px 8px 8px;
        text-decoration: none;
        font-size: 25px;
        color: #818181;
        transition: 0.3s;
    }

    #sidenav-bar a:hover {
        color: #f1f1f1;
    }

    #sidenav-context {
        position: absolute;
        right: -100px;
        width: 340px;           /* Side Navigation Bar - This should be same. */
    }
    /* Side Navigation Bar Context Link End */

    /* Others from Navigation Bar Start */
    #sidenav-others {
        width: 100%;
        max-width: 100%;
        margin-left: 50px;
        padding: 5px;
        transition: 0.5s;
    }

    #sidenav-others.sidenav-others-open {
        margin-left: 240px;     /* Side Navigation Bar - This should be same. */
    }

    .row div {
        width: 400px;
    }
    /* Others from Navigation Bar End */

    /* Side Navigation Button Start */
    #btn-nav {
        top: -5px;
        right: -5px;
        position: absolute;
    }

    .btn-nav-icon1, .btn-nav-icon2, .btn-nav-icon3 {
        width: 35px;
        height: 5px;
        background-color: #818181;
        margin: 6px 6px;
        transition: 0.5s;
    }

    .btn-nav-hover {
        background-color: #f1f1f1;
    }    

    .btn-nav-toggle .btn-nav-icon1 {
        transform: translate(0px, 11px) rotate(-45deg);
    }

    .btn-nav-toggle .btn-nav-icon2 {
        opacity: 0;
    }

    .btn-nav-toggle .btn-nav-icon3 {
        transform: translate(0px, -11px) rotate(45deg);
    }
    /* Side Navigation Button End */
</style>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Clinic Service System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datatables")
    @Scripts.Render("~/bundles/jquery-ui")
    @Scripts.Render("~/bundles/select2")

    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("健保特約診所查詢系統", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("關於", "About", "Home")</li>
                    <li>@Html.ActionLink("連絡人", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div id="sidenav-others" class="container body-content">
        <div id="sidenav-bar">
            <a id="btn-nav" href="#">
                <div class="btn-nav-icon1"></div>
                <div class="btn-nav-icon2"></div>
                <div class="btn-nav-icon3"></div>
            </a>
            <div id="sidenav-context">
                <div>@Html.ActionLink("診所查詢功能", "Index", "ClinicQuery")</div>
                <div>@Html.ActionLink("分享評論功能", "Index", "Feedback")</div>
            </div>
        </div>
        <div>
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 健保特約診所查詢系統</p>
        </footer>
    </div>
</body>
</html>

<script type="text/javascript">
    // Side Navigation Bar Event Start _____
    $('#btn-nva').hover(function () {
        $('[class^="btn-nav-icon"]').toggleClass('btn-nav-hover');
    }, function () {
        $('[class^="btn-nav-icon"]').toggleClass('btn-nav-hover');
    });

    $('#btn-nav').on('click', function () {
        $('#btn-nav').toggleClass('btn-nav-toggle');
        $('#sidenav-bar').toggleClass('sidenav-bar-open');
        $('#sidenav-others').toggleClass('sidenav-others-open');
    });
    // Side Navigation Bar Event End _____

    // Global Function Start _____
    // Get the data form the selector by form element.
    function GetFormObj(selector) {
        var result = {};
        var data = $(selector).serializeArray();

        $.each(data, function (idx, e) {
            if (result[e.name] == undefined)
                result[e.name] = e.value;
            else
                result[e.name] += ',' + e.value;
        });

        return result;
    };
    // Global Function End _____
</script>