ClinicServiceSystem/Controllers/ClinicQueryTestController.cs
using System.Data;
using System.Text;
using System.Web.Mvc;

namespace ClinicServiceSystem.Controllers
{
    public class ClinicQueryTestController : SharedController
    {
        // GET: ClinicQuery
        override public ActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult Test(string param)
        {
            string strResult;

            strResult = "Your Input is: " + param;

            return new JsonResult { Data = strResult };
        }

        [HttpPost]
        public ActionResult Search(string clinicName, string a, string b, string c, string d, string e)
        {
            string strResult;
            DataTable dt = new DataTable();

            // Todo: Query from datatbase.
            #region Make fake data
            dt.Columns.Add("ClinicName");
            dt.Columns.Add("ClinicId");

            dt.Rows.Add("Clinic1", "00001");
            dt.Rows.Add("Clinic2", "00002");
            #endregion

            strResult = ExportDatatableToHtml(dt);

            return new JsonResult { Data = strResult };
        }

        string ExportDatatableToHtml(DataTable dt)
        {
            StringBuilder strHtmlBuilder = new StringBuilder();

            strHtmlBuilder.Append("<html>");
            strHtmlBuilder.Append("<head>");
            strHtmlBuilder.Append("</head>");
            strHtmlBuilder.Append("<body>");
            strHtmlBuilder.Append("<table border='1px' cellpadding='1' cellspacing='1' bgcolor='lightyellow' style='font-family:Garamond; font-size:smaller'>");
            strHtmlBuilder.Append("<tr>");

            foreach (DataColumn dc in dt.Columns)
            {
                strHtmlBuilder.Append("<td>");
                strHtmlBuilder.Append(dc.ColumnName);
                strHtmlBuilder.Append("</td>");
            }

            strHtmlBuilder.Append("</tr>");
            
            foreach (DataRow dr in dt.Rows)
            {
                strHtmlBuilder.Append("<tr>");

                foreach (DataColumn dc in dt.Columns)
                {
                    strHtmlBuilder.Append("<td>");
                    strHtmlBuilder.Append(dr[dc.ColumnName].ToString());
                    strHtmlBuilder.Append("</td>");
                }
                strHtmlBuilder.Append("</tr>");
            }
            
            strHtmlBuilder.Append("</table>");
            strHtmlBuilder.Append("</body>");
            strHtmlBuilder.Append("</html>");

            string strHtml = strHtmlBuilder.ToString();

            return strHtml;
        }
    }
}

ClinicServiceSystem/Controllers/FeedbackTestController.cs
using System.Web.Mvc;

namespace ClinicServiceSystem.Controllers
{
    public class FeedbackTestController : SharedController
    {
        // GET: Feedback
        override public ActionResult Index()
        {
            return View();
        }
    }
}

ClinicServiceSystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClinicServiceSystem.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ClinicServiceSystem/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ClinicServiceSystem/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ClinicServiceSystem/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>健保特約診所查詢系統</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>診所查詢-測試區</h2>
        <p>
            我們的第一個查詢功能~
        </p>
        <p>@Html.ActionLink("前往~ GoGo!", "Index", "ClinicQueryTest", null, new { @class = "btn btn-success" })</p>
    </div>
    <div class="col-md-4">
        <h2>分享評論-測試區</h2>
        <p>
            來看看大家的評論吧~
        </p>
        <p>@Html.ActionLink("前往~ GoGo!", "Index", "FeedbackTest", null, new { @class = "btn btn-success" })</p>
    </div>
    <div class="col-md-4">
        <h2>查詢功能3</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>